[package]
name = "bevy_garage_ios"
version = "0.1.0"
edition = "2021"
description = "bavy_garage ios"
publish = false
license = "MIT OR Apache-2.0"

[lib]
name = "bavy_garage"
crate-type = ["staticlib"]

[dependencies]
bevy = { workspace = true }
bevy_garage = { path = "../" }
