[package]
name = "car_sim"
version = "0.1.0"
edition = "2021"
description = "Car sim with bevy and rapier"
publish = false
license = "MIT OR Apache-2.0"

[lib]
name = "car_sim"
crate-type = ["staticlib"]

[dependencies]
# bevy = { workspace = true }
bevy = { version = "0.9.1" }
